cp ~/.bash_profile ./
cp ~/.bashrc    ./
cp ~/.gemrc     ./
cp ~/.gitconfig ./
cp ~/.gitignore_global ./
cp ~/.my.cnf    ./
cp ~/.profile   ./
cp ~/.spring.rb ./
cp ~/.tmux.conf ./
cp ~/.vimrc     ./
cp ~/.zshrc     ./
cp ~/.zlogin    ./
